spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: none
    open-in-view:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog-master.xml
    default-schema: public
    liquibase-schema: public
    clear-checksums: on
  mail:
    host: smtp.gmail.com
    port: 587
    username: smdovn42@gmail.com
    password: lgrvgizrhsoauhbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
   auth:
     whitelist: >
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,  
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**,
      /v3/api-docs/**,
      /v3/api-docs,
      /swagger-ui/**,
      /v2/api-docs,
      /api/v1/public/**,
      /ws-registration/**,
      /api/v3/accounts/**
